name: Build Plugin
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Download BakkesMod SDK
      run: |
        git clone https://github.com/bakkesmodorg/BakkesMod2-Plugins.git sdk
        echo "BAKKESMOD_SDK=$((Get-Item .).FullName)\sdk" >> $env:GITHUB_ENV

    - name: Build Solution
      run: |
        # Creamos el archivo de versión manualmente para evitar que falle el script de powershell
        New-Item -Path "WhosBottingPlugin" -Name "version.h" -ItemType "file" -Value "" -Force
        msbuild WhosBottingPlugin.sln /p:Configuration=Release /p:Platform="x64" /p:BakkesModPath="${{ env.BAKKESMOD_SDK }}" /p:PreBuildEvent=

    - name: Upload Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Plugin-Files
        path: |
          **/*.dll
          **/*.set
